# Generated by Django 3.2.2 on 2021-05-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet_service", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactionlogs", old_name="wallet_id", new_name="wallet",
        ),
        migrations.AlterField(
            model_name="transactionlogs",
            name="operation",
            field=models.CharField(
                choices=[
                    ("c", "Create"),
                    ("d", "Deposit"),
                    ("w", "Withdrawal"),
                    ("r", "Receive"),
                    ("s", "Send"),
                ],
                max_length=1,
            ),
        ),
    ]
