# Generated by Django 3.2.2 on 2021-05-11 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='homeworkresult',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.human'),
        ),
        migrations.AddField(
            model_name='homeworkresult',
            name='homework',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='firstapp.homework'),
        ),
    ]
